AllCops:
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/ClassVars:
  Enabled: false

Metrics/AbcSize:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 100
Metrics/ClassLength:
  Max: 110
Metrics/ModuleLength:
  Max: 110
Metrics/MethodLength:
  Max: 50
Metrics/BlockLength:
  Max: 100
Metrics/PerceivedComplexity:
  Max: 50
Layout/LineLength:
  Max: 140

